# Debug mode. Enables debug controllers,
# auth testing users and verbose logging
debug: true
spring:

    # Liquibase setup
    liquibase:
        change-log: classpath:db/changelog/changelog-master.json
        contexts: test
        test-rollback-on-update: on


    # H2 database setup
    datasource:
        driver-class-name: org.h2.Driver
        url: "jdbc:h2:mem:database;\
              DB_CLOSE_DELAY=-1;\
              DB_CLOSE_ON_EXIT=TRUE;"
        username: admin
        password: password
    jpa:
        properties:
            hibernate:
                # This is needed in order to fix an issue with h2 console auth
                # This represents the schema where all the business logic is held
                default_schema: insurance_manager
    h2:
        # Enable this to enable H2 console web application.
        # (debug mode needs to be enabled for this to work)
        console:
            enabled: true
            path: /debug/db
