#
# Spring Boot configuration for development environment
#
spring:
    # Liquibase setup for H2 database
    liquibase:
        change-log: classpath:/db/changelog/changelog-master.json
        url: jdbc:h2:mem:java_internship;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
        contexts: test
        user: sa
        password: admin
    # H2 database setup
    datasource:
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-console
    # Additional settings
    # main:
    #     banner-mode: off
    # jpa:
    #     open-in-view: false
    
