spring:
    profiles:
        active: local
    # Liquibase setup
    liquibase:
        change-log: classpath:db/changelog/changelog-master.json
        contexts: test
        test-rollback-on-update: true
    # H2 database setup
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:java_internship;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
        username: sa
        password: admin
        name: java_internship
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                '[default_schema]': insurance_manager
        hibernate:
            ddl-auto: update
    # Enable this for development purposes only!
    h2:
        console:
            enabled: true
            path: /h2-console