#
# Spring Boot configuration for development environment
#
spring:
    # Liquibase setup
    liquibase:
        change-log: classpath:db/changelog/changelog-master.json
        contexts: test
    # H2 database setup
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:java_internship;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
        username: sa
        password: admin
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    h2:
        # Enable this for development purposes only!
        console:
            enabled: true
            path: /h2-console
    # Additional settings
    # main:
    #     banner-mode: off
    # jpa:
    #     open-in-view: false
    
